### ISSUE TITLE
Finish productionizing gem

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/folio_client#1]
Gem is already:
* versioned
* has test coverage (assuming 92% is cool)
* in sul-dlss org

Needs:
- [x] license - DONE already, see https://github.com/sul-dlss/folio_client/blob/main/LICENSE
- [x] publish to RubyGems - DONE already https://rubygems.org/gems/folio_client/
- [x] add to access-update-scripts (see https://github.com/sul-dlss/access-update-scripts/pull/217)
- [x] #dlss-sdr-github slack connection

**Comment by peetucket** [comment]
Note: the reduction in test coverage is because of the minimal testing of the `UnexpectedReponse` class, which currently has a decent percent of the total number of lines of code at the moment, but is rather uninteresting to test.
