### ISSUE TITLE
Research requirements and methods for handling data import failures

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/folio_client#28]
This a research ticket to answer the questions:
1) If a data import job fails, what are the requirements for communicating that failure back to the consumer? 

Is it enough to say: "There was an error, here's the job ID (or a link to look it up in the UI)"?  Example UI screen:
![image](https://user-images.githubusercontent.com/1619369/222474047-c95c451a-56e1-4331-9d7a-fe3345b193c2.png)

2) If we want to return more specific error information to the consumer, what API calls are required to get this information? 

@jermnelson suggested [GET /metadata-provider/jobLogEntries/{jobExecutionId}](https://s3.amazonaws.com/foliodocs/api/mod-source-record-manager/p/metadata-provider.html#metadata_provider_joblogentries__jobexecutionid__get).

**Comment by justinlittman** [comment]
Given the complexity of reading from the jobLogEntries endpoint and that import failure of programmatically created ETD MARC records is unlikely, I would propose that our initial approach should be to raise an error with appropriate context.

I'd propose that the error message should be: "Record import failed. See the import log in Folio for job execution id <JOB_EXECUTION_ID> for more information."

If in the future a different approach is merited, then we can revisit the jobLogEntries endpoint.

**Comment by justinlittman** [comment]
Updated https://github.com/sul-dlss/hydra_etd/issues/1391 with the outcome of this ticket.
