### ISSUE TITLE
Research: how to look up in FOLIO that an ETD has been cataloged

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/folio_client#6]
@arcadiafalcone recommends we stay with the current check of location being INTERNET. This ticket is to determine what API calls we should make to FOLIO to see if the location for an ETD is INTERNET. 

This depends on us having retrieved the instance HRID after the stub was loaded and having that to use in looking up the record. 

~~@shelleydoljack @ahafele: where do you recommend that we find the location for ETDs in FOLIO, both migrated and imported in the future?~~

Action for this ticket, as of 2023-02-15 11:39am PST:

given an HRID, how use OKAPI to know a record is cataloged?   Can we use "instance status" of cataloged to tell?

@arcadiafalcone ^^ can you check with Vitus on this?`

**Comment by ahafele** [comment]
We are no longer using the location INTERNET. 
Location information will be in the holdings record in folio for electronic resources. ETDs will have a permanent location of SUL-SDR. They will have a Instance status of "cataloged" when done. They will also have a Instance stat code of E-THESIS. I believe there is still a question of temporary location usage. Cataloging workflow should be confirmed with Vitus.

**Comment by shelleydoljack** [comment]
> Location information will be in the holdings record in folio for electronic resources. ETDs will have a permanent location of SUL-SDR. They will have a Instance status of "cataloged" when done. They will also have a Instance stat code of E-THESIS. I believe there is still a question of temporary location usage. Cataloging workflow should be confirmed with Vitus.

@ahafele do we have a ticket to set instance status "cataloged" for migrated records? i'm not seeing this in the facet in Inventory app on folio-test:

![Screen Shot 2023-02-15 at 11 36 16 AM](https://user-images.githubusercontent.com/6343464/219121598-1c1ac2bc-3ec6-4de6-89b2-ccaae712d996.png)

**Comment by ahafele** [comment]
There is now :) - https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/308.

**Comment by ndushay** [comment]
@arcadiafalcone:  Would you please check with (Vitus?)  on whether we can look for "instance status" of cataloged to tell if an ETD has been cataloged?   Or otherwise confer with the Folio libsys wise ones about this?

**Comment by ndushay** [comment]
@arcadiafalcone assigning this to you, but after we know exactly what to look for in folio, then put back in new issues column and remove "question" label, as this will likely become the research ticket for OKAPI calls.

**Comment by shelleydoljack** [comment]
I found an ETD in folio-test and edited some of the fields we are missing (statistical code and instance status) because we haven't set those yet in our migration process. https://folio-test.stanford.edu/inventory/view/e040a790-ec4e-5366-8460-447c9194d4b2?qindex=hrid&query=a12854819&sort=title

To query the statistical code "E-THESIS" and instance status = "cataloged": `/search/instances?query=(statisticalCodeIds=="0f328803-cd6a-47c0-8e76-f3a775d56884" and statusId=="9634a5ab-9228-4703-baf2-4d12ebc77d56")`

The UUID's for statistical code and instance status should be the same across folio environments. To get the values on instance statuses: `/instance-statuses` and to get the values of statistical codes: `/statistical-codes?limit=100` . You can also do things like `/statistical-codes?query=code="E-THESIS"` and `/instance-statuses?query=name=="Cataloged"`

**Comment by lwrubel** [comment]
@shelleydoljack thanks for looking up these API calls-- this is really helpful. 

Can you explain what that means that you "edited some of the fields we are missing (statistical code and instance status) because we haven't set those yet in our migration process"? Is setting the statistical code and instance status a new process that catalogers will be doing once cataloging in FOLIO, but migrated data does not reflect that?

**Comment by shelleydoljack** [comment]
It would be a new process for catalogers in FOLIO (something that Vitus and Metadata folks should confirm) and our migration scripts are not adding that data yet to the instance records.

**Comment by arcadiafalcone** [comment]
Per Vitus the ETD workflow has not been established yet, so there's not a clear answer to this for now. We're working towards a decision.

**Comment by arcadiafalcone** [comment]
From Vitus: the instance status code changing to `cat` will be the sign that cataloging is complete.

> Arcadia, the Folio Metadata subgroup has discussed the topic of how to signify that a title is cataloged in Folio. It has agreed to use a common method for that, and the method is to update the Instance status code/term as shown in the picture below (code “cat”, term “Cataloged”). So, ETD procedure should use that to determine whether am ETD record has been cataloged or still inprocess

**Comment by arcadiafalcone** [comment]
@lwrubel I do not have the power to remove the question tag.

**Comment by lwrubel** [comment]
@shelleydoljack Thanks for adding an instance status code and instance status term to an ETD record. 

Based on that, I can see that we can look up an instance by HRID and get back an instance record:
`/instances?query=hrid==a13250145"`

If that record has an instance status, it will be in the instance's `statusId` and for `cat` status code it will have a value of `9634a5ab-9228-4703-baf2-4d12ebc77d56` as shared above.  If the record doesn't have a status, and it sounds like we don't know yet whether all records will get one on import, then there will not be a `statusId` code.

**Comment by lwrubel** [comment]
Closing since we've determined the UUID to look for and the methods to use.
